before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - 6
      - 7

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      
  - image_templates:
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/AstroFloof/{{ .ProjectName }}:latest-arm64v8"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
